version: '2'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    environment:
      - MYSQL_DATABASE=concerto
      - MYSQL_USER=concerto
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Europe/London
    volumes:
      - ./data/mysql:/var/lib/mysql

  concerto:
    image: campsych/concerto-platform:5.0.beta.6
    container_name: concerto
    restart: on-failure
    volumes:
      - ./data/concerto:/data
    environment:
      - CONCERTO_PASSWORD=admin
      - CONCERTO_CONTENT_URL=.
      - CONCERTO_PLATFORM_URL=/
      - CONCERTO_GIT_REPOSITORY_PATH=/data/git
      - DB_HOST=database
      - DB_PASSWORD=changeme
      - TZ=Europe/London
    ports:
      - "80:80"
